version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"   # or "3.11" if you prefer

mkdocs:
  configuration: mkdocs.yml   # ← change to "docs/mkdocs.yml" if yours is inside docs/ folder

python:
  install:
    - requirements: requirements.txt
